name: NightMarket
version: '${version}'
main: me.byteful.plugin.nightmarket.NightMarketPlugin
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - EssentialsX
  - EcoBits
author: byteful
description: A plugin that brings a limited-access, rotating shop to Minecraft. Supports Vault and has an easy-to-use developer API for other plugins.
permissions:
  nightmarket.admin:
    description: "Permission to use all NightMarket admin commands."
  nightmarket.use:
    description: "Permission to use /nightmarket"
    default: true
